#ifndef COMMON_STATUS_CODES_H
#define COMMON_STATUS_CODES_H

#include "status.h"
#include "status_facility.h"

// Common
#define STATUS_INVALID_ARGUMENT \
    STATUS_MAKE(STATUS_SEV_ERROR, FACILITY_COMMON, SCOPE_GENERAL)

#define STATUS_NOT_IMPLEMENTED \
    STATUS_MAKE(STATUS_SEV_ERROR, FACILITY_COMMON, SCOPE_GENERAL)

// Memory
#define STATUS_OUT_OF_MEMORY \
    STATUS_MAKE(STATUS_SEV_ERROR, FACILITY_MEMORY, SCOPE_MM)

// File
#define STATUS_NOT_FOUND \
    STATUS_MAKE(STATUS_SEV_ERROR, SCOPE_FS, FILE_NOT_FOUND)

// Font
#define STATUS_INVALID_PSF2_MAGIC \
    STATUS_MAKE(STATUS_SEV_ERROR, SCOPE_GFX, FONT_PSF2_INVALID_MAGIC)

#define STATUS_INVALID_PSF2_HEADER \
    STATUS_MAKE(STATUS_SEV_ERROR, FACILITY_FONT, 0x0002)

#define STATUS_UNSUPPORTED_PSF2_VERSION \
    STATUS_MAKE(STATUS_SEV_ERROR, FACILITY_FONT, 0x0003)

#endif